<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ParameterSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['paraKode' => 'Ag (Perak) -', 'paraNama' => 'Ag (Perak) -'],
            ['paraKode' => 'Al1', 'paraNama' => 'Al (Aluminium) - Tanah, air'],
            ['paraKode' => 'As (Arsen)', 'paraNama' => 'As (Arsen)'],
            ['paraKode' => "Autoclave\r\n", 'paraNama' => "Autoclave\r\n"],
            ['paraKode' => 'Ba1', 'paraNama' => 'Ba (Barium) - Tanah, air'],
            ['paraKode' => 'Biosafety Cabinet', 'paraNama' => 'Biosafety Cabinet'],
            ['paraKode' => 'Ca (Kalsium)', 'paraNama' => 'Ca (Kalsium)'],
            ['paraKode' => 'Cd', 'paraNama' => 'Cd (tanah,air,pangan, non pangan)'],
            ['paraKode' => 'cek', 'paraNama' => 'cek'],
            ['paraKode' => 'Co1', 'paraNama' => 'Co (Kobal) - Tanah, air'],
            ['paraKode' => 'Colony Counter Digit', 'paraNama' => 'Colony Counter Digital'],
            ['paraKode' => 'Cr', 'paraNama' => 'Cr (tanah,air,pangan,non pangan)'],
            ['paraKode' => 'Cu', 'paraNama' => 'Cu (tanah,air,pangan,non pangan)'],
            ['paraKode' => 'Cu1', 'paraNama' => 'Cu (Tembaga) - Tanah, air, pupuk cair'],
            ['paraKode' => 'EKSTRAKSI', 'paraNama' => 'MASERASI'],
            ['paraKode' => 'EKSTRAKSI-1', 'paraNama' => 'SOXHLETASI'],
            ['paraKode' => 'EKSTRAKSI-2', 'paraNama' => 'FRAKSINASI'],
            ['paraKode' => 'ELISA READER-0', 'paraNama' => 'MIKROPLATE ELISA'],
            ['paraKode' => 'ELISA READER-1', 'paraNama' => 'PEMBACAAN ELISA'],
            ['paraKode' => 'ELISA-1', 'paraNama' => 'Pembacaan Elisa'],
            ['paraKode' => 'ELISA-2', 'paraNama' => 'MIKROPLATE ELISA'],
            ['paraKode' => 'Fasilitas Magang', 'paraNama' => 'Fasilitas Magang'],
            ['paraKode' => 'Fasilitas Pelatihan ', 'paraNama' => 'Fasilitas Pelatihan '],
            ['paraKode' => 'Fe1', 'paraNama' => 'Fe (Besi) - Tanah, air'],
            ['paraKode' => 'Freezers', 'paraNama' => "Freezers suhu -20 to -40°C \r\n"],
            ['paraKode' => 'FTIR', 'paraNama' => 'FTIR'],
            ['paraKode' => 'FTIR-1', 'paraNama' => 'Preparasi Sampel'],
            ['paraKode' => 'FTIR-2', 'paraNama' => 'Preparasi dan Pengujian'],
            ['paraKode' => 'FTIR-3', 'paraNama' => 'Preparasi Sampel baru'],
            ['paraKode' => 'Furnace', 'paraNama' => "Furnace muffle up to 1400°C \r\n"],
            ['paraKode' => 'GCMS0', 'paraNama' => 'GCMSD'],
            ['paraKode' => 'GCMS1', 'paraNama' => 'GCMSHS'],
            ['paraKode' => 'Hg (Merkuri)', 'paraNama' => 'Hg (Merkuri)'],
            ['paraKode' => 'HPLC-0', 'paraNama' => 'SCANNING'],
            ['paraKode' => 'HPLC-1', 'paraNama' => 'KAFEIN'],
            ['paraKode' => 'HPLC-2', 'paraNama' => 'KUARSETIN '],
            ['paraKode' => 'HPLC-3', 'paraNama' => 'ASAM GALAT '],
            ['paraKode' => 'K (Kalium)', 'paraNama' => 'K (Kalium)'],
            ['paraKode' => 'Laminar Airflow', 'paraNama' => 'Laminar Airflow'],
            ['paraKode' => 'Lemari Pengering', 'paraNama' => 'Lemari Pengering'],
            ['paraKode' => 'lidan', 'paraNama' => 'lidan jua'],
            ['paraKode' => 'Manifold Vakum SPE', 'paraNama' => 'Manifold Vakum SPE'],
            ['paraKode' => 'Mg (Magnesium)', 'paraNama' => 'Mg (Magnesium)'],
            ['paraKode' => 'Mikroskop', 'paraNama' => 'Mikroskop'],
            ['paraKode' => 'MIKROSKOP-0', 'paraNama' => 'FOTO PREPARAT'],
            ['paraKode' => 'Mn1', 'paraNama' => 'Mn (Mangan) - Tanah, air, pupuk cair'],
            ['paraKode' => 'Na (Natrium)', 'paraNama' => 'Na (Natrium)'],
            ['paraKode' => 'NGS', 'paraNama' => 'NGS'],
            ['paraKode' => 'Ni (Nikel)', 'paraNama' => 'Ni (Nikel)'],
            ['paraKode' => 'Orbital Shaker', 'paraNama' => 'Orbital Shaker'],
            ['paraKode' => 'Pb', 'paraNama' => 'Pb (tanah,air,pangan,non pangan)'],
            ['paraKode' => 'Pelatihan', 'paraNama' => 'Fasilitasi Pelatihan'],
            ['paraKode' => 'Pencetak Tablet Manu', 'paraNama' => 'Pencetak Tablet Manual'],
            ['paraKode' => 'pH', 'paraNama' => 'pH (air, tanah, dll)'],
            ['paraKode' => 'pH Meter', 'paraNama' => 'pH Meter'],
            ['paraKode' => 'PROKSIMAT', 'paraNama' => 'PROKSIMAT(Air, Abu, Protein kasar, Lemak, Karbohidrat, & Serat kasar)'],
            ['paraKode' => 'PROKSIMAT-0', 'paraNama' => 'KADAR AIR'],
            ['paraKode' => 'PROKSIMAT-1', 'paraNama' => 'KADAR ABU'],
            ['paraKode' => 'PROKSIMAT-2', 'paraNama' => 'KADAR PROTEIN'],
            ['paraKode' => 'PROKSIMAT-3', 'paraNama' => 'KADAR LEMAK'],
            ['paraKode' => 'PROKSIMAT-4', 'paraNama' => 'KADAR SERAT KASAR'],
            ['paraKode' => 'PROKSIMAT-5', 'paraNama' => 'KADAR KARBOHIDRAT'],
            ['paraKode' => 'RefMikro', 'paraNama' => 'Refrigerated Mikrocentrifuge'],
            ['paraKode' => 'Rotary Evaporatore', 'paraNama' => 'Rotary Evaporatore'],
            ['paraKode' => 'Rotary Vakum Evapora', 'paraNama' => 'Rotary Vakum Evaporator'],
            ['paraKode' => 'RT PCR', 'paraNama' => 'RT PCR'],
            ['paraKode' => 'Ruang Lab', 'paraNama' => 'Ruang Lab'],
            ['paraKode' => 'Ruang Rapat untuk Wo', 'paraNama' => 'Ruang Rapat untuk Workshop/Seminar/Diskusi/Lokakarya/Pelatihan/ Praktikum Fullday'],
            ['paraKode' => 'SAA', 'paraNama' => 'SAA (ADSOPRSI-DESORPSI)'],
            ['paraKode' => 'Se (Selenium)', 'paraNama' => 'Se (Selenium)'],
            ['paraKode' => 'SEM', 'paraNama' => 'SEM MORFOLOGI'],
            ['paraKode' => 'SEM 1', 'paraNama' => 'SEM 1'],
            ['paraKode' => 'SEM-EDX', 'paraNama' => 'SEM-EDX'],
            ['paraKode' => 'Sewa Alat (Freeze Dr', 'paraNama' => 'Sewa Alat (Freeze Dryer)'],
            ['paraKode' => 'Sewa Alat (Oven)', 'paraNama' => 'Sewa Alat (Oven)'],
            ['paraKode' => 'Sewa Alat (Refrigera', 'paraNama' => 'Sewa Alat (Refrigeratore Suhu 1-12 °C)'],
            ['paraKode' => 'Sewa Alat (Thermosta', 'paraNama' => 'Sewa Alat (Thermostate Incubator)'],
            ['paraKode' => 'Sewa Autoclave', 'paraNama' => 'Sewa Autoclave'],
            ['paraKode' => 'Shaker TS-100', 'paraNama' => 'Shaker TS-100'],
            ['paraKode' => 'Shieve Machine', 'paraNama' => 'Shieve Machine'],
            ['paraKode' => 'SPEKTRO UV VIS', 'paraNama' => 'Preparasi Sampel UV Vis'],
            ['paraKode' => 'spektro uv-vis 10', 'paraNama' => 'ASAM HUMAT'],
            ['paraKode' => 'T (testing)', 'paraNama' => 'Nah anu'],
            ['paraKode' => 'TEXTURE-1', 'paraNama' => 'KEKERASAN'],
            ['paraKode' => 'UV Clean Box', 'paraNama' => 'UV Clean Box'],
            ['paraKode' => 'UV-VIS-0', 'paraNama' => 'SCANNING UV VIS'],
            ['paraKode' => 'UV-VIS-1', 'paraNama' => 'TOTAL FENOLIK'],
            ['paraKode' => 'UV-VIS-10', 'paraNama' => 'VITAMIN K'],
            ['paraKode' => 'UV-VIS-11', 'paraNama' => 'SULFAT (air)'],
            ['paraKode' => 'UV-VIS-12', 'paraNama' => 'Total Flavanoid'],
            ['paraKode' => 'UV-VIS-2', 'paraNama' => 'ANTIOKSIDAN (IC50)'],
            ['paraKode' => 'UV-VIS-3', 'paraNama' => 'KLOROFIL'],
            ['paraKode' => 'UV-VIS-4', 'paraNama' => 'TOTAL TANIN'],
            ['paraKode' => 'UV-VIS-5', 'paraNama' => 'KURKUMIN'],
            ['paraKode' => 'UV-VIS-6', 'paraNama' => 'ASAM FOLAT'],
            ['paraKode' => 'UV-VIS-7', 'paraNama' => 'VITAMIN A'],
            ['paraKode' => 'UV-VIS-8', 'paraNama' => 'VITAMIN C'],
            ['paraKode' => 'UV-VIS-9', 'paraNama' => 'VITAMIN E'],
            ['paraKode' => 'VISKOSITAS', 'paraNama' => 'NILAI VISKOSITAS'],
            ['paraKode' => 'Vortex Biosan Latvia', 'paraNama' => 'Vortex Biosan Latvia'],
            ['paraKode' => 'Vortex plus Mini Cen', 'paraNama' => 'Vortex plus Mini Centrifuge'],
            ['paraKode' => 'Waterbath Shaker', 'paraNama' => 'Waterbath Shaker'],
            ['paraKode' => 'Workshop/Seminar/Dis', 'paraNama' => 'Ruang Rapat untuk Workshop/Seminar/Diskusi/Lokakarya/Pelatihan/ Praktikum Halfday'],
            ['paraKode' => 'Zn1', 'paraNama' => 'Zn (Seng) - Tanah, air'],
        ];

        $this->db->table('simlab_r_parameter')->insertBatch($data);
    }
}
