<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SimlabAccountUsersSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'user_id'       => 2,
                'role_id'       => 2,
                'user_name'     => 'user',
                'user_email'    => 'user1@gmail.com',
                'user_password' => '$2y$10$z3DzozFcF/ZchfRxvPhPW.oHr0RNSqK5izeV4iw04rm1rwFMBH49C',
                'status_user'   => 1,
                'user_identity' => 'ULM',
            ],
            [
                'user_id'       => 4,
                'role_id'       => 2,
                'user_name'     => 'testingajah',
                'user_email'    => 'testing@gmail.com',
                'user_password' => '$2y$10$qJGhSMazaAIY6m6MQd/vSOJ9K6pXP0FS1qOoSfHwN4KaQvrvAKHxi',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 5,
                'role_id'       => 2,
                'user_name'     => 'coba',
                'user_email'    => 'coba@gmail.com',
                'user_password' => '$2y$10$CYlWJRhJhulHtzV5Rcusr.r2KRV7qYhgnk58jmSf4jrEmVA9axe9S',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 6,
                'role_id'       => 2,
                'user_name'     => 'faisal akbar',
                'user_email'    => '2311016210023@mhs.ulm.ac.id',
                'user_password' => '$2y$10$K8GxKhtrkU6P.qdZKgbqH.CUc/wTBnR4JXN6VijDFBLIIXkvv9lcO',
                'status_user'   => 1,
                'user_identity' => 'ULM',
            ],
            [
                'user_id'       => 7,
                'role_id'       => 2,
                'user_name'     => 'ical',
                'user_email'    => 'ical@gmail.com',
                'user_password' => '$2y$10$EODtPe6ITh30sTMYc8naqOPVwNwsA1qkWHKc/sq6dkHp0Cb0eat/G',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 8,
                'role_id'       => 2,
                'user_name'     => 'mawar',
                'user_email'    => 'mawar@gmail.com',
                'user_password' => '$2y$10$bAoMS3bolDEFfcsDyT6gYu4QYIzcMijRS4MnwQueHC3lICb//1qSe',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 9,
                'role_id'       => 2,
                'user_name'     => 'ceka',
                'user_email'    => 'ceka@gmail.com',
                'user_password' => '$2y$10$3LDd6DfPxNSzTGARoV1fAOQLW27Ti4VOQ8ccof6qpZuP/B21Huo8K',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 10,
                'role_id'       => 2,
                'user_name'     => 'cekaa',
                'user_email'    => 'cekaaa@gmail.com',
                'user_password' => '$2y$10$cgmMArg1GgBRrl.Ok0DLE.rsimNAoB2U0JuaX/EEjxwKD38Q.7LYm',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 11,
                'role_id'       => 2,
                'user_name'     => 'ca',
                'user_email'    => 'ca@gmail.com',
                'user_password' => '$2y$10$0WHol/S4/LPWa1H/tlJwi.sl/XoCm.jdg9aP9bvf2E12xKFlKXed.',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 12,
                'role_id'       => 2,
                'user_name'     => 'icalicul',
                'user_email'    => 'icul@gmail.com',
                'user_password' => '$2y$10$tdSfvwMCXpxpRdldmzQ.0uiDg9xKVBqnZdWpOWy5GfHmgiR4SgKFy',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 13,
                'role_id'       => 2,
                'user_name'     => 'iculicul',
                'user_email'    => 'iculicul@gmail.com',
                'user_password' => '$2y$10$3.X8rZq0wnDFdZP3qcGVX.tRmSJv4hJhSGAFmwFXW3IBft.gBQUqa',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 15,
                'role_id'       => 2,
                'user_name'     => 'f',
                'user_email'    => 'f@gmail.com',
                'user_password' => '$2y$10$.QAYc6B1nMWo9pMJL2SlhOxpXMBR4V5NLu9nn.cXfRI3dmcgbVDuW',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 16,
                'role_id'       => 2,
                'user_name'     => 'f',
                'user_email'    => 'f1@gmail.com',
                'user_password' => '$2y$10$HXyflwjLcaz15gNVlsrIBefM/tCaCv6Fv6UbD4e17F1iwsryzH5SK',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 17,
                'role_id'       => 3,
                'user_name'     => 'cek4',
                'user_email'    => 'cek4@gmail.com',
                'user_password' => '$2y$10$IfQR71o2.bUOfNMkVJ0BAOa4Ug1mpbGAcUnnx1OoK2XRr9N/edwne',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 18,
                'role_id'       => 3,
                'user_name'     => 'cek4',
                'user_email'    => 'misal@gmail.com',
                'user_password' => '$2y$10$KwxXP1z8WVGQ469NqoCDUuAxHy/RgvGj57gu/ECICgpIXIA3X71Ra',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 19,
                'role_id'       => 2,
                'user_name'     => 'lk',
                'user_email'    => 'lk@gmail.com',
                'user_password' => '$2y$10$Xh5OMB7Jho6DXNvl1tNjSemHgpiPTKzgXlTdpfUZpbtEUI/JgBhe2',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 20,
                'role_id'       => 2,
                'user_name'     => 'lk1',
                'user_email'    => 'lk1@gmail.com',
                'user_password' => '$2y$10$FuA3GWOKX71SXkzMHjhj.OJc.sTvZZlkmvGiyme/u7Tcw/WBVBq42',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 21,
                'role_id'       => 2,
                'user_name'     => 'faisal',
                'user_email'    => 'fa@gmail.com',
                'user_password' => '$2y$10$Iq/xB7OEi7Y8e7U4Dbu9r.CHyFMFGkhvH8NBtOB0Fdn5ETmmaGIma',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 22,
                'role_id'       => 2,
                'user_name'     => 'icil',
                'user_email'    => 'cil@gmail.com',
                'user_password' => '$2y$10$.Eruo.AZBWC0GZPq6gWfyOoYkNGx2NX0Ox9mer/4MevdvOdtzjHPq',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 23,
                'role_id'       => 2,
                'user_name'     => 'cihuy',
                'user_email'    => 'chiuy@gmail.com',
                'user_password' => '$2y$10$p2SyeKDoAHD2J4r54ctMyuZ7Izuiyv9RthVhkSDxZhd3JMkCXRPsO',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
            [
                'user_id'       => 24,
                'role_id'       => 2,
                'user_name'     => 'h',
                'user_email'    => 'h@gmail.com',
                'user_password' => '$2y$10$Q1DPXEx0wcflmAOOZZWUU.1KDGB/lfKxcP1gds9dfDJScnWU5GZUK',
                'status_user'   => 1,
                'user_identity' => 'NON ULM',
            ],
        ];

        // insert batch
        $this->db->table('simlab_account_users')->insertBatch($data);
    }
}
